version: "3"

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    network_mode: service:db
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forms_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: